#!/bin/bash

host="10.42.42.222"
port="9100"

width="$(curl -s http://10.42.42.222/general/status.html | grep -Po '\d+mm' | grep -Po '\d+')"
size="$(($width*160/24))"
size="$(($size<128?$size:128))"
echo "$width"mm tape detected, resizing to "$size"px

convert -background white "$1" -sample x"$size" -gravity center -extent x128 pbm:- | "$(dirname "$(readlink -f "$0")")/ptouch-770-write" $width | nc $host $port
